name: static-graphics-musl-zig

on:
  workflow_call:
    inputs:
      skiasharp_version:
        required: true
        type: string
      source_lock:
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      skiasharp_version:
        type: string
        default: '3.119.4'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/static-graphics-zig-cross.yml
    with:
      skiasharp_version: ${{ inputs.skiasharp_version }}
      source_lock: ${{ inputs.source_lock || '' }}
      rids: '["linux-musl-x64","linux-musl-arm64"]'
